import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Regenerates the dashboard's static Combat Achievement completion-rate table
 * from `data/combat-achievements.csv` (a raw wiki export).
 *
 * The RuneProfile API supplies every other field (tier, type, monster,
 * description) so the only thing we keep here is the community completion
 * percentage, which has no API source and must be refreshed by hand.
 */

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const CSV_PATH = path.resolve(__dirname, "../../data/combat-achievements.csv");
const OUT_PATH = path.resolve(
  __dirname,
  "../../dashboard/src/data/caCompletion.ts",
);

/** Minimal RFC-4180 CSV reader (quoted fields, escaped quotes, CRLF). */
function parseCsv(text: string): string[][] {
  const rows: string[][] = [];
  let row: string[] = [];
  let cur = "";
  let quoted = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (quoted) {
      if (c !== '"') {
        cur += c;
      } else if (text[i + 1] === '"') {
        cur += '"';
        i++;
      } else {
        quoted = false;
      }
      continue;
    }
    if (c === '"') quoted = true;
    else if (c === ",") {
      row.push(cur);
      cur = "";
    } else if (c === "\n") {
      row.push(cur);
      rows.push(row);
      row = [];
      cur = "";
    } else if (c !== "\r") {
      cur += c;
    }
  }
  if (cur.length || row.length) {
    row.push(cur);
    rows.push(row);
  }
  return rows.filter((r) => r.some((cell) => cell.trim().length > 0));
}

function parsePercent(raw: string): number | null {
  const m = raw.trim().match(/^([\d.]+)\s*%$/);
  if (!m) return null;
  const n = Number(m[1]);
  return Number.isFinite(n) ? n : null;
}

async function main(): Promise<void> {
  const raw = await fs.readFile(CSV_PATH, "utf8");
  const rows = parseCsv(raw.replace(/^\uFEFF/, ""));
  const header = rows[0].map((h) => h.trim().toLowerCase());
  const nameIdx = header.indexOf("name");
  const pctIdx = header.findIndex((h) => h.startsWith("comp"));
  if (nameIdx < 0 || pctIdx < 0) {
    throw new Error(
      `combat-achievements.csv must have "Name" and "Comp%" columns, got: ${header.join(", ")}`,
    );
  }

  const entries: Array<[string, number | null]> = [];
  const seen = new Set<string>();
  let naCount = 0;
  for (const row of rows.slice(1)) {
    const name = row[nameIdx]?.trim();
    if (!name) continue;
    if (seen.has(name)) {
      console.warn(`[ca-completion] duplicate task name in CSV: ${name}`);
      continue;
    }
    seen.add(name);
    const pct = parsePercent(row[pctIdx] ?? "");
    if (pct === null) naCount++;
    entries.push([name, pct]);
  }
  entries.sort((a, b) => a[0].localeCompare(b[0]));

  const body = entries
    .map(([name, pct]) => `  ${JSON.stringify(name)}: ${pct === null ? "null" : pct},`)
    .join("\n");

  const out = `// AUTO-GENERATED by \`npm run ca:completion\` — do not edit by hand.
// Source: data/combat-achievements.csv (raw OSRS Wiki export).
// Regenerate whenever the dashboard warns about tasks missing a completion rate.

/**
 * Community completion rate (percent of players) per Combat Achievement task,
 * keyed by the task name as reported by the RuneProfile API.
 * \`null\` means the wiki reports N/A for that task.
 */
export const CA_COMPLETION: Readonly<Record<string, number | null>> = {
${body}
};
`;

  await fs.mkdir(path.dirname(OUT_PATH), { recursive: true });
  await fs.writeFile(OUT_PATH, out, "utf8");
  console.log(
    `[ca-completion] wrote ${entries.length} tasks (${naCount} N/A) to ${path.relative(process.cwd(), OUT_PATH)}`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
